apiVersion: v1
kind: Pod
metadata:
  name: nginx-downwardapi
  namespace: default
  labels:
    app: nginx
    env: demo
spec:
  containers:
    - name: app
      image: nginx:1.25
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "250m"
          memory: "64Mi"
        limits:
          cpu: "500m"
          memory: "128Mi"
      volumeMounts:
        - name: pod-info
          mountPath: /etc/podinfo

  volumes:
    - name: pod-info
      downwardAPI:
        items:
          - path: "pod-name"
            fieldRef:
              fieldPath: metadata.name
          - path: "pod-namespace"
            fieldRef:
              fieldPath: metadata.namespace
          - path: "pod-ip"
            fieldRef:
              fieldPath: status.podIP
          - path: "node-name"
            fieldRef:
              fieldPath: spec.nodeName
          - path: "cpu-limit"
            resourceFieldRef:
              containerName: app
              resource: limits.cpu
          - path: "memory-limit"
            resourceFieldRef:
              containerName: app
              resource: limits.memory
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels